# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['cloud.py'],
    pathex=[],
    binaries=[],
    datas=[('data', 'data'),
           ('ui/images', 'ui/images'),
           ('ui/js', 'ui/js'),
           ('ui/models', 'ui/models'),
           ('reports/fonts', 'reports/fonts'),
           ('users.json', '.'),
           ('env_config.txt', '.'),
           ('icon.ico', '.'),
           ('ui/ads_banner.html', 'ui')],
    hiddenimports=['PySide6.QtWebEngineWidgets',
                   'PySide6.QtSvg',
                   'PySide6.QtPrintSupport',
                   'nest_asyncio',
                   'core.db',
                   'core.engine',
                   'core.licensing',
                   'core.models',
                   'core.optimize',
                   'core.security',
                   'core.specs',
                   'core.thread_worker',
                   'core.utils',
                   'core.validators',
                   'core.ai.chat_service',
                   'core.ai.providers.base',
                   'core.ai.providers.gemini_provider',
                   'core.rag.embedder',
                   'core.rag.index',
                   'core.rag.pdf_loader',
                   'core.rag.schema',
                   'core.utils.paths',
                   'core.utils.trough_utils',
                   'core.utils.unit_conversion',
                   'reports.exporter_excel',
                   'reports.exporter_pdf',
                   'reports.templates',
                   'ui.activation_dialog',
                   'ui.ad_banner_widget',
                   'ui.login_dialog',
                   'ui.main_window_3d_enhanced',
                   'ui.plotting',
                   'ui.styles',
                   'ui.tooltips',
                   'ui.ui_components_3d_enhanced',
                   'ui.visualization_3d',
                   'ui.chat.chat_panel'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    [],
    [],
    name='ConveyorCalculator',
    debug=False,
    icon='icon.ico',
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    name='ConveyorCalculator',
)
